### ISSUE TITLE
Missing function definition

### ISSUE THREAD

**Issue by Robotechnic** [astrale-sharp/wasm-minimal-protocol#19]
I just started to create a wasm plugin for typst but I'm getting errors when I import the plugin and run a function:
```
error: cannot find definition for import env::__syscall_faccessat with type Func(FuncType { params: [I32, I32, I32, I32], results: [I32] })
```
You can see the sources [here](https://github.com/Robotechnic/graphviz-typst)

I can't find any solutions and don't know why it doesn't work because Graphviz works perfectly for standard web usage.

It may be a silly mistake but I can't figure it out.

**Comment by astrale-sharp** [comment]
Have you run the stubber here https://github.com/astrale-sharp/wasm-minimal-protocol/blob/master/wasi-stub ? :)

Graphviz might depend on the browser emulating a filesystem for it, which would not be supported by typst

**Comment by arnaudgolfouse** [comment]
You can stub arbitrary functions btw: you could try
```sh
wasi-stub --stub-function env:__syscall_faccessat …
```

**Comment by Robotechnic** [comment]
Thank you, it's working now.

**Comment by Robotechnic** [comment]
Yes,
I stubbed two functions:
- env:__syscall_unlinkat
- env:__syscall_faccessat
I don't know why but now it works as expected and I don't see any problem related to this.

**Comment by astrale-sharp** [comment]
If the problem comes back with other people we'll probably add those to what we're stubbing then!
